### ISSUE TITLE
Query in OpenFn job returns result in wrapper format

### ISSUE THREAD

**Issue by Shraddha-Ingale** [OpenFn/myAgro#1]
Hi,
I want to use Id of upserted parent record to related it with its child records, However observed that OpenFn doesn't return Salesforce Id on the update operation, 
As the solution I tried to fetch Id of parent record by the query using external id. I used the same syntax for query as provided in OpenFn documentation but the query returning the result in wrapper format.
Can you please help me with proper query format, To fetch salesforce records in the form of array?

**Comment by taylordowns2000** [comment]
Hi @Shraddha-Ingale , I'm moving this over to our community group (https://groups.google.com/forum/#!topic/openfn/wsG_EX-FmPA) and will answer there. I don't follow this repository, but you're welcome to use it for your own issue tracking :-)
