### ISSUE TITLE
Timeout after Salesforce query

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/myAgro#5]
## Issue
See the run failure: https://www.openfn.org/projects/myagro/runs/061ead91-eb67-72fe-99cf-6f47218becff
I'm not sure if this is a sandbox data-related issue, or something with the OpenFn job. Please run locally and see how long it takes. 

## state
See LP for `myAgro Salesforce Sandbox (Integration)`

## expression
(Note that this doesn't looked link to Github... I will ask myAgro to be added to the repo.)
https://www.openfn.org/projects/myagro/jobs/jvgkk8

**Comment by aleksa-krolls** [comment]
@lakhassane myAgro changed the user permissions. Can you please try running locally again?

**Comment by aleksa-krolls** [comment]
@lakhassane myAgro changed the user permissions... can you please run this job again to check if anything changed?

**Comment by taylordowns2000** [comment]
My initial reaction to our testing is that this sandbox has some API version or API settings that are incompatible with `language-salesforce`, which is something we'd should address post haste.

We can run `describe('Voucher__c')` with Oauth and jsForce via that webUI, but seemingly not with the security token for that user via `language-salesforce`.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 @lakhassane can you try running this same job with the admin user `myAgro Sandbox (Admin user - Integrate)`? This will help us 100% rule out that it's not a sandbox issue... but rather something user-specific.

**Comment by aleksa-krolls** [comment]
Looks like it's an issue with the SF user permissions. Closing for now.
